AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - '**/schema.rb'
    - '**/db/migrate/**'
    - '**/examples/**/*'
    - '**/bin/*'


Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/YodaCondition:
  Enabled: false
