# require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'examples/**'

# BEGIN
Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
# END
